export const stadiumReservationAbi = [
  {
    type: "function",
    name: "MAX_SEATS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "SEATS_PER_ROW",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "NUM_ROWS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "baseURI",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "basePrices",
    stateMutability: "view",
    inputs: [{ type: "uint256" }, { type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "getSeatByIndex",
    stateMutability: "view",
    inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "eventId", type: "uint256" },
          { name: "section", type: "uint256" },
          { name: "row", type: "uint256" },
          { name: "seatNumber", type: "uint256" },
          { name: "price", type: "uint256" },
          { name: "tokenId", type: "uint256" },
          { name: "isReserved", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "seatTokenId",
    stateMutability: "view",
    inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "reserveSeat",
    stateMutability: "payable",
    inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "reserveSeat",
    stateMutability: "payable",
    inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "string" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "reserveSeatsBatch",
    stateMutability: "payable",
    inputs: [
      {
        name: "requests",
        type: "tuple[]",
        components: [
          { name: "eventId", type: "uint256" },
          { name: "section", type: "uint256" },
          { name: "row", type: "uint256" },
          { name: "seatNumber", type: "uint256" },
        ],
      },
    ],
    outputs: [{ type: "uint256[]" }],
  },
  {
    type: "function",
    name: "reserveSeatsBatch",
    stateMutability: "payable",
    inputs: [
      {
        name: "requests",
        type: "tuple[]",
        components: [
          { name: "eventId", type: "uint256" },
          { name: "section", type: "uint256" },
          { name: "row", type: "uint256" },
          { name: "seatNumber", type: "uint256" },
        ],
      },
      { name: "metadataURIs", type: "string[]" },
    ],
    outputs: [{ type: "uint256[]" }],
  },
  {
    type: "function",
    name: "resaleSeat",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256" }, { type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "tokenURI",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "setBasePrice",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSeatPrice",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setBaseURI",
    stateMutability: "nonpayable",
    inputs: [{ type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "SeatReserved",
    anonymous: false,
    inputs: [
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
      { indexed: false, name: "eventId", type: "uint256" },
      { indexed: false, name: "section", type: "uint256" },
      { indexed: false, name: "row", type: "uint256" },
      { indexed: false, name: "seatNumber", type: "uint256" },
      { indexed: false, name: "price", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "SeatResale",
    anonymous: false,
    inputs: [
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: true, name: "newOwner", type: "address" },
      { indexed: false, name: "resalePrice", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "SeatMetadataSet",
    anonymous: false,
    inputs: [
      { indexed: true, name: "tokenId", type: "uint256" },
      { indexed: false, name: "metadataURI", type: "string" },
    ],
  },
] as const;
